- README.md
- package-lock.json
- package.json
- react/index.js
- install package `eslint-plugin-typescript-enum@2.1.0`
- extend react configuration with `typescript-enum/recommended`
- update documentation
> feat(react): disallow the use of TypeScript enums

- base/index.js
By default, the [`import/no-unused-modules`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unused-modules.md#importno-unused-modules) rule is used to indicate missing and unused exports. However, this is not necessary for all files and it comes to positive false reports. With appropriate adjustments this rule is switched off for certain files.
> fix(eslint-plugin): [import/no-unused-modules] ignore rule on specified files

- base/index.js
- use the tsconfig.json nearest each source file
> fix(eslint-plugin): [parserOptions] improve monorepo support

- base/index.js
- base/strict.js
- package-lock.json
- package.json
This PR update all dependencies. It especially updates typescript-eslint to version 6. Following the [Announcement/Migration guide](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6#user-facing-breaking-changes) I also migrated the rulesets `recommended` and `recommended-requiring-type-checks` to `recommended-type-checked`, added the ruleset `stylistic-type-checked` to the base config and migrated `strict` to `strict-type-checked`.
> Updating to typescript-eslint@6

- .eslintrc.js
- README.md
- base/index.js
- package-lock.json
- package.json
- react/index.js
- add eslint-plugin-perfectionist
- remove eslint-plugin-sort-keys-plus
- disable the following rules in favor of eslint-plugin-perfectionist
- import/order
- sort-imports
- @typescript-eslint/adjacent-overload-signatures
- sort-keys
- @typescript-eslint/sort-type-constituents
- activate rulset perfectionist/recommended-natural
- configure perfectionist/sort-imports similar as import/order before
- configure perfectionist/sort-jsx-props similar as react/jsx-sort-props before
BREAKING CHANGE: add eslint-plugin-perfectionist and remove eslint-plugin-sort-keys-plus
> feat: add eslint-plugin-perfectionist

- package.json
- include `lib` folder into publishing files
> build(npm): fix missing lib module

- base/index.js
- enable the "@typescript-eslint/consistent-type-imports" rule to enforce consistent import styles for TypeScript types.
- reference: https://johnnyreilly.com/typescript-5-importsnotusedasvalues-error-eslint-consistent-type-imports
BREAKING CHANGE: Enforces a new import style for TypeScript types
> feat(typescript): enable "@typescript-eslint/consistent-type-imports" rule

- base/index.js
- lib/eslint-plugin-perfectionist.js
In PR #16 we introduced some custom configurations for perfectionist/sort-classes. These configurations also overwrite the groups configuration which was not intended.
> Reenable recommended groups configuration of perfectionist/sort-classes

- base/index.js
As discussed, this enables reporting of unused ignore comments.
I discovered, that this also seems to be auto-fixable (at least with our project configuration in VS Code settings.json).
> Report unused disable directives (eslint-ignore)

- package-lock.json
- package.json
- bump package @typescript-eslint/eslint-plugin from ^6.21.0 to ^7.2.0
- bump package @typescript-eslint/parser from ^6.21.0 to ^7.2.0
- bump peer dependencies eslint from ^8.54.0 to ^8.56.0
BREAKING CHANGE: update to typescript-eslint@7
> feat: update package typescript-eslint@7

- base/index.js
- package-lock.json
- package.json
- bump package @commitlint/cli from 19.2.1 to 19.3.0
- bump package @commitlint/config-conventional from 19.1.0 to 19.2.2
- bump package @rushstack/eslint-patch from ^1.10.1 to ^1.10.2
- bump package @typescript-eslint/eslint-plugin from ^7.6.0 to ^7.7.1
- bump package @typescript-eslint/parser from ^7.6.0 to ^7.7.1
- bump package eslint-plugin-perfectionist from ^2.8.0 to ^2.10.0
- bump package eslint-plugin-playwright from ^1.5.4 to ^1.6.0
- bump package semantic-release from 23.0.7 to 23.0.8
- extend the new rule `perfectionist/sort-intersection-types` for natural sorting with ignoring the lower/upper case
> chore(deps): update dependencies

- .husky/commit-msg
- package-lock.json
- package.json
- bump package husky from 9.0.11 to 9.1.1
- bump package prettier from 3.3.2 to 3.3.3
- perform recommended migration steps for husky, see: https://github.com/typicode/husky/releases/tag/v9.1.1
> chore(deps): update dev dependencies

- README.md
- base/index.js
- package-lock.json
- package.json
BREAKING CHANGE: add 'eslint-plugin-deprecation' to base configuration
> feat(base): add 'eslint-plugin-deprecation' to report usage of deprecated code

- base/index.js
- lib/eslint-plugin-perfectionist.js
- package-lock.json
- package.json
- perform required migration steps, see: https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.0.0
- remove customized rules that covers natural sorting and ignore case sensitive as it is covered by the new configuration
- add initial group to sort intersection-types
BREAKING CHANGE: update to eslint-plugin-perfectionist@3
> feat(deps): update eslint-plugin-perfectionist@3

- base/index.js
The dot-notation of eslint conflicts with the noPropertyAccessFromIndexSignature property of the TS configuration. typescript-eslint fixes this already. Therefor switching to this rule. (See https://typescript-eslint.io/rules/dot-notation/).
> Switching from eslint dot-notation to @typescript-eslint/dot-notation

- README.md
- package-lock.json
- package.json
- prettier-disable/index.js
This PR adds another shared config, which wraps [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) (which disables rules that are not necessary or not compatible with prettier). It reenables some rules which are compatible with our specific config.
> Adds a prettier-disable shared config

- package.json
Adds the prettier-disable folder to the files array in package.json to be published.
> Fix prettier disable config

- CHANGELOG.md
- README.md
- configs/base.js
- package-lock.json
- package.json
- following recommendation from typescript-eslint: https://typescript-eslint.io/packages/parser#project
> feat(base): [typescript-eslint] update parserOptions to use projectService instead of project

- configs/react.js
- with eslint-plugin-perfectionist@4 the support of glob pattern was removed in favor of regex which leads to unintended sorting of the props, see: https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v4.0.0
> fix(react): [sort-jsx-props] use regex pattern for custom groups

- package-lock.json
- package.json
- bump package @eslint/js from ^9.17.0 to ^9.18.0
- bump package eslint-config-prettier from ^9.1.0 to ^10.0.1
- bump package eslint-plugin-react from ^7.37.3 to ^7.37.4
- bump package eslint-plugin-react-refresh from ^0.4.16 to ^0.4.18
- bump package typescript-eslint from ^8.19.1 to ^8.20.0
> feat(deps): update dependencies

- configs/base.js
this rule is currently not compatible with flat-configs. It should be reactivated ASAP
> fix(base): turn off import/no-unused-modules for now

- configs/base.js
- package-lock.json
- package.json
- the current pattern also matched non-javascript files and let the complete process fail because the rule can only be applied to javascript files
- update dependencies
> fix(config): [base] update test file patterns to only match javascript files

- CHANGELOG.md
- README.md
- configs/playwright.js
- package-lock.json
- package.json
- update documentation how to use the configuration only for specific files
> feat(playwright): disable unbound-method rule for component testing compatibility

- configs/base.js
- fix(base): remove redundant no-empty-function rule from base config
this rule is implemented as a replacement in typescript-eslint and therefore also disabled in the typescript-eslint recommended config. enabling this rule again manually only leads to redundant problem messages
- refactor(base): remove redundant rules prefer-const and prefer-rest-params
those are already configured in the recommended and stylistic configs of typescript-eslint
> Remove redundant rules
